const prop = require("../build/index.node");

const PropertyKey = {
    "AppUserModelID": "System.AppUserModel.ID",
    "AppUserModelParentID": "System.AppUserModel.ParentID",
    "AppZoneIdentifier": "System.AppZoneIdentifier",
    "AudioChannelCount": "System.Audio.ChannelCount",
    "AudioEncodingBitrate": "System.Audio.EncodingBitrate",
    "AudioFormat": "System.Audio.Format",
    "AudioSampleRate": "System.Audio.SampleRate",
    "AudioSampleSize": "System.Audio.SampleSize",
    "AudioStreamNumber": "System.Audio.StreamNumber",
    "Author": "System.Author",
    "Comment": "System.Comment",
    "ComputerName": "System.ComputerName",
    "ContentType": "System.ContentType",
    "DRMIsProtected": "System.DRM.IsProtected",
    "DateAccessed": "System.DateAccessed",
    "DateCreated": "System.DateCreated",
    "DateImported": "System.DateImported",
    "DateModified": "System.DateModified",
    "DocumentDateCreated": "System.Document.DateCreated",
    "DocumentDateSaved": "System.Document.DateSaved",
    "ExpandoProperties": "System.ExpandoProperties",
    "FileAttributes": "System.FileAttributes",
    "FileAttributesDisplay": "System.FileAttributesDisplay",
    "FileExtension": "System.FileExtension",
    "FileName": "System.FileName",
    "FileOwner": "System.FileOwner",
    "FilePlaceholderStatus": "System.FilePlaceholderStatus",
    "IsFolder": "System.IsFolder",
    "IsShared": "System.IsShared",
    "ItemAuthors": "System.ItemAuthors",
    "ItemDate": "System.ItemDate",
    "ItemFolderNameDisplay": "System.ItemFolderNameDisplay",
    "ItemFolderPathDisplay": "System.ItemFolderPathDisplay",
    "ItemFolderPathDisplayNarrow": "System.ItemFolderPathDisplayNarrow",
    "ItemName": "System.ItemName",
    "ItemNameDisplay": "System.ItemNameDisplay",
    "ItemNameDisplayWithoutExtension": "System.ItemNameDisplayWithoutExtension",
    "ItemParticipants": "System.ItemParticipants",
    "ItemPathDisplay": "System.ItemPathDisplay",
    "ItemPathDisplayNarrow": "System.ItemPathDisplayNarrow",
    "ItemType": "System.ItemType",
    "ItemTypeText": "System.ItemTypeText",
    "Kind": "System.Kind",
    "KindText": "System.KindText",
    "LastWriterPackageFamilyName": "System.LastWriterPackageFamilyName",
    "LinkTargetExtension": "System.Link.TargetExtension",
    "LinkTargetParsingPath": "System.Link.TargetParsingPath",
    "LinkTargetSFGAOFlags": "System.Link.TargetSFGAOFlags",
    "LinkTargetSFGAOFlagsStrings": "System.Link.TargetSFGAOFlagsStrings",
    "MIMEType": "System.MIMEType",
    "MediaDuration": "System.Media.Duration",
    "MusicAlbumID": "System.Music.AlbumID",
    "MusicAlbumTitle": "System.Music.AlbumTitle",
    "MusicDisplayArtist": "System.Music.DisplayArtist",
    "NetworkLocation": "System.NetworkLocation",
    "NotUserContent": "System.NotUserContent",
    "OfflineAvailability": "System.OfflineAvailability",
    "OfflineStatus": "System.OfflineStatus",
    "ParsingName": "System.ParsingName",
    "ParsingPath": "System.ParsingPath",
    "PerceivedType": "System.PerceivedType",
    "SFGAOFlags": "System.SFGAOFlags",
    "SecurityAllowedEnterpriseDataProtectionIdentities": "System.Security.AllowedEnterpriseDataProtectionIdentities",
    "SecurityEncryptionOwners": "System.Security.EncryptionOwners",
    "SecurityEncryptionOwnersDisplay": "System.Security.EncryptionOwnersDisplay",
    "ShareScope": "System.ShareScope",
    "SharedWith": "System.SharedWith",
    "SharingStatus": "System.SharingStatus",
    "ShellSFGAOFlagsStrings": "System.Shell.SFGAOFlagsStrings",
    "Size": "System.Size",
    "StorageProviderAggregatedCustomStates": "System.StorageProviderAggregatedCustomStates",
    "SyncTransferStatusFlags": "System.SyncTransferStatusFlags",
    "ThumbnailCacheId": "System.ThumbnailCacheId",
    "Title": "System.Title",
    "VideoCompression": "System.Video.Compression",
    "VideoEncodingBitrate": "System.Video.EncodingBitrate",
    "VideoFourCC": "System.Video.FourCC",
    "VideoFrameHeight": "System.Video.FrameHeight",
    "VideoFrameRate": "System.Video.FrameRate",
    "VideoFrameWidth": "System.Video.FrameWidth",
    "VideoHorizontalAspectRatio": "System.Video.HorizontalAspectRatio",
    "VideoIsSpherical": "System.Video.IsSpherical",
    "VideoIsStereo": "System.Video.IsStereo",
    "VideoOrientation": "System.Video.Orientation",
    "VideoStreamNumber": "System.Video.StreamNumber",
    "VideoTotalBitrate": "System.Video.TotalBitrate",
    "VideoVerticalAspectRatio": "System.Video.VerticalAspectRatio",
    "VolumeId": "System.VolumeId",
    "ZoneIdentifier": "System.ZoneIdentifier"
}

const read = async (file) => await prop.read(file);
const getValue = async (file, key) => await prop.getValue(file, PropertyKey[key]);
const getValues = async (files, key) => await prop.getValue(files, PropertyKey[key]);
const setValue = async (file, key, value) => await prop.setValue(file, PropertyKey[key], value);

module.exports = { read, getValue, getValues, setValue };
